/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#d2bbff',
        'on-primary': '#3f008e',
        'primary-container': '#7c3aed',
        'on-primary-container': '#ede0ff',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        'inverse-primary': '#732ee4',
        'surface-tint': '#d2bbff',
        secondary: '#89ceff',
        'on-secondary': '#00344d',
        'secondary-container': '#00a2e6',
        'on-secondary-container': '#00344e',
        'secondary-fixed': '#c9e6ff',
        'secondary-fixed-dim': '#89ceff',
        'on-secondary-fixed': '#001e2f',
        'on-secondary-fixed-variant': '#004c6e',
        tertiary: '#ffb784',
        'on-tertiary': '#4f2500',
        'tertiary-container': '#a15100',
        'on-tertiary-container': '#ffe0cd',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb784',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#713700',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#0b1326',
        'on-background': '#dae2fd',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#ccc3d8',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        outline: '#958da1',
        'outline-variant': '#4a4455',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-lg': '40px',
        'margin-sm': '16px',
        gutter: '24px',
        unit: '4px',
        'container-max': '1440px',
      },
      fontFamily: {
        // Inter carries no CJK glyphs, so chain OS-native CJK faces after it;
        // Latin renders in Inter, Chinese falls through to PingFang/YaHei/Noto.
        'display-lg': ['Inter', 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'sans-serif'],
        'body-md': ['Inter', 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'sans-serif'],
        'headline-lg': ['Inter', 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
